[profile.default]
src = "src"
out = "out"
test = "tests"
libs = ["lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[profile.ci]
src = "src"
out = "out"
test = "tests"
libs = ["lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
fuzz = { runs = 256 }
verbosity = 3


[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types = "long"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"


[rpc_endpoints]
base = "${RPC_BASE}"